{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluxor.fullname" . }}-config
  labels:
    {{- include "fluxor.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.config.content | nindent 4 }}
{{- end }}
